INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr101@gmail.com', NOW() - INTERVAL 7 DAY, 'NONE');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr102@gmail.com', NOW() - INTERVAL 7 DAY, 'NONE');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr103@gmail.com', NOW() - INTERVAL 7 DAY, 'IN_PROGRESS');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr104@gmail.com', NOW() - INTERVAL 7 DAY, 'SENT');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr105@gmail.com', NOW() - INTERVAL 3 DAY, 'NONE');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr106@gmail.com', NOW() - INTERVAL 3 DAY, 'IN_PROGRESS');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr107@gmail.com', NOW() - INTERVAL 3 DAY, 'SENT');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr108@gmail.com', NOW() - INTERVAL 1 DAY, 'NONE');

