INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr101@gmail.com', NOW() - INTERVAL 7 DAY, 'SENT');
INSERT INTO t (EMAIL, NOTIFICATION_DATE, STATUS_OF_NEXT) VALUES ('testaddr101@gmail.com', NOW() - INTERVAL 1 DAY, 'NONE');

